### ISSUE TITLE
Question regarding evaluation

### ISSUE THREAD

**Issue by isalirezag** [fanyix/STMN#1]
Than you for sharing the implementation of the code.
I have a question regarding the evaluation process.
In the VID dataset some of the frames does not have any object in them and the xml file does not have any bbox gt for them, can you please elaborate what did you do in the evaluation process for those frames? did you simply ignore them or did something else?
Thanks

**Comment by fanyix** [comment]
For frames that do not have any object, all detections will be considered as false positives when computing mAP.
