### ISSUE TITLE
A doubt about the MatchTrans

### ISSUE THREAD

**Issue by Feywell** [fanyix/STMN#4]
I remember the formula as follow：
![MatchTrans](https://user-images.githubusercontent.com/24384298/51451006-1d7f4980-1d6e-11e9-8640-1e30bc5e57be.png)

need to set k to control the size of the matching vicinity. But I do not see k in **MatchTrans.lua**

**Comment by fanyix** [comment]
The k in the paper corresponds to "pad" variable in this line: https://github.com/fanyix/STMN/blob/b19e54e3526acaa173bd5f10584195bd064ef17b/modules/MatchTrans.lua#L13

**Comment by Feywell** [comment]
@fanyix  Thank you！I'm not familiar with torch. I just try to understand your code.
