### ISSUE TITLE
understanding parallelization

### ISSUE THREAD

**Issue by shady-cs15** [fanyix/STMN#5]
What is the right way to parallelize the evaluation?

I took the default launcher.py script and made some changes for passing in additional arguments like ckpt and model_path.

```
import subprocess
import os
import time

# number of procs
proc_N = 2
gpu_id = [2,3]
eval_type = 'rfcn' # 'stmn'

file = 'eval_detect_full.lua'
assert proc_N == len(gpu_id)

# launch processes
for proc in range(0, proc_N):
    my_env = os.environ.copy()
    my_env["CUDA_VISIBLE_DEVICES"] = '%g' % gpu_id[proc]
    my_env["CUDNN_PATH"] = '/usr1/schakra1/packages/anaconda2/envs/lua/lib/libcudnn.so.7'
    my_env["THC_CACHING_ALLOCATOR"] = '1' # '0' for memory-saving mode

    cmd = ['th', 'scripts/%s' % file, '-task', '%g' % proc, '-model', eval_type, '-model_path', '../dataset/ImageNetVID/models/%s.t7' %eval_type, '-ckpt', '%s_testing' %eval_type]
    subprocess.Popen(cmd, env=my_env)
    print('%g/%g process launched' % (proc, proc_N))
    time.sleep(3)
```

The evaluation is running but I don't see how the data is parallelized. It seems like it is running 4 processes on the same validation data not on different chunks of it. Am I missing something?

**Comment by fanyix** [comment]
This script is supposed to parallelize the evaluation across multiple GPUs (one GPU per process). It achieves so by writing locks to disk (each process takes one video at a time). Can you check whether it is writing locks properly?
