### ISSUE TITLE
out of memery

### ISSUE THREAD

**Issue by zhaowujie** [fanyix/STMN#6]
I only have a 12GB gpu, how to modify the parameters to avoid the problem of out of memory @fanyix

**Comment by shady-cs15** [comment]
+1 It trains for a few hours and then it runs out of memory. Is there some memory leak happening?
![Screenshot 2019-04-05 at 5 51 13 PM](https://user-images.githubusercontent.com/10852861/55658372-6cfcdf80-57cb-11e9-9154-1d6d0f7684a9.png)

**Comment by fanyix** [comment]
Hi, you can try changing "timestep_per_batch" in training config (config.lua) to a smaller value to reduce memory consumption.

**Comment by zhaowujie** [comment]
I'll try , thanks a lot!
